# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

stages:
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress

run_tests:
  image: cypress/base:10
  stage: test
  script: 
    - npm ci
    - npm run ci
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 day


deploy_to_stage:
  stage: deploy
  tags:
    - brew-installed
  environment:
    name: staging
  script:
    - brew install awsebcli
    - eb deploy parlay-island-frontend-stage
  only:
    - master

deploy_to_prod:
  stage: deploy
  tags:
    - brew-installed
  environment:
    name: prod
  when: manual
  script:
    - brew install awsebcli
    - eb deploy parlay-island-frontend-prod
